import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-terms',
  standalone: true,
  imports: [RouterLink],
  template: `
    <div class="legal">
      <a routerLink="/" class="back">&larr; Back to EquityLens</a>
      <h1>Terms of Service</h1>
      <p class="updated">Last updated: 29 March 2026</p>

      <section>
        <h2>Acceptance of Terms</h2>
        <p>By accessing or using EquityLens ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.</p>
      </section>

      <section>
        <h2>Description of Service</h2>
        <p>EquityLens is a free, open-source ASX stock analysis tool that scores publicly listed companies based on financial ratios and sector-specific models. The Service is provided as a portfolio project and educational resource.</p>
      </section>

      <section>
        <h2>Not Financial Advice</h2>
        <p><strong>EquityLens does not provide financial, investment, or trading advice.</strong> All scores, ratings, and analysis are generated by automated models for informational and educational purposes only. They should not be relied upon to make investment decisions.</p>
        <p>You should consult a qualified financial adviser before making any investment decisions. We are not licensed financial advisers and accept no responsibility for any losses incurred from using the Service.</p>
      </section>

      <section>
        <h2>Accuracy of Data</h2>
        <p>Financial data is sourced from third-party providers (including Yahoo Finance) and may be delayed, incomplete, or inaccurate. We make no guarantees about the accuracy, completeness, or timeliness of any data displayed on the Service.</p>
      </section>

      <section>
        <h2>User Accounts</h2>
        <p>You may sign in using Google or GitHub. You are responsible for maintaining the security of your account. We reserve the right to suspend or terminate accounts that violate these terms.</p>
      </section>

      <section>
        <h2>Acceptable Use</h2>
        <p>You agree not to:</p>
        <ul>
          <li>Use the Service for any unlawful purpose</li>
          <li>Attempt to access other users' data or accounts</li>
          <li>Scrape, crawl, or use automated tools to extract data from the Service at scale</li>
          <li>Attempt to disrupt or overload the Service's infrastructure</li>
          <li>Redistribute data from the Service commercially without permission</li>
        </ul>
      </section>

      <section>
        <h2>Intellectual Property</h2>
        <p>The EquityLens source code is open-source. The scoring models, configurations, and curated content are the intellectual property of the project maintainers.</p>
      </section>

      <section>
        <h2>Limitation of Liability</h2>
        <p>The Service is provided "as is" without warranties of any kind, express or implied. To the fullest extent permitted by law, we shall not be liable for any direct, indirect, incidental, or consequential damages arising from your use of the Service.</p>
      </section>

      <section>
        <h2>Availability</h2>
        <p>We do not guarantee that the Service will be available at all times. We may modify, suspend, or discontinue the Service at any time without notice.</p>
      </section>

      <section>
        <h2>Changes to Terms</h2>
        <p>We may update these Terms at any time. Continued use of the Service after changes constitutes acceptance of the updated Terms.</p>
      </section>

      <section>
        <h2>Governing Law</h2>
        <p>These Terms are governed by the laws of Australia. Any disputes shall be resolved in the courts of Australia.</p>
      </section>

      <section>
        <h2>Contact</h2>
        <p>For questions about these Terms, contact us at <a href="mailto:adstar3108@gmail.com">adstar3108&#64;gmail.com</a>.</p>
      </section>
    </div>
  `,
  styles: [`
    :host { display: block; }
    .legal {
      max-width: 720px;
      margin: 0 auto;
      padding: 2rem 1.5rem 4rem;
      color: var(--text-primary);
      font-family: 'Inter', system-ui, sans-serif;
      line-height: 1.7;
    }
    .back {
      display: inline-block;
      margin-bottom: 1.5rem;
      color: var(--accent);
      text-decoration: none;
      font-size: 0.875rem;
      &:hover { text-decoration: underline; }
    }
    h1 {
      font-size: 1.75rem;
      font-weight: 700;
      margin: 0 0 0.25rem;
    }
    .updated {
      color: var(--text-muted);
      font-size: 0.8125rem;
      margin: 0 0 2rem;
    }
    h2 {
      font-size: 1.1rem;
      font-weight: 600;
      margin: 2rem 0 0.5rem;
      color: var(--text-primary);
    }
    p, li {
      color: var(--text-secondary);
      font-size: 0.9375rem;
    }
    ul {
      padding-left: 1.25rem;
      margin: 0.5rem 0;
    }
    li { margin: 0.25rem 0; }
    a { color: var(--accent); }
    section { margin-bottom: 0.5rem; }
  `],
})
export class TermsComponent {}
